[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0

; Configuración específica para tu versión N8 (8MB Flash, No PSRAM)
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_upload.flash_size = 8MB

; Librerías desde GitHub para evitar el UnknownPackageError
lib_deps = 
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git